/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/UnitTests/JUnit5TestClass.java to edit this template
 */
package com.mycompany.chat;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 *
 * @author mmaka
 */



public class ChatTest {

    @Test
    public void testAutoGeneratedMessageIDLength() {
        Chat.Message m = new Chat.Message("0837597589", "Hello world");
        // Auto-generated ID should always be 10 digits
        assertEquals(10, m.messageID.length());
    }

    @Test
    public void testRecipientFormatSuccess() {
        Chat.Message m = new Chat.Message("0837597589", "Hi Keegan");
        assertTrue(m.checkRecipientCell());
    }

    @Test
    public void testRecipientFormatFailure() {
        Chat.Message m = new Chat.Message("ABC123", "Hi Keegan");
        assertFalse(m.checkRecipientCell());
    }

    @Test
    public void testMessageLengthSuccess() {
        String msg = "Short message under 250 chars.";
        Chat.Message m = new Chat.Message("0837597589", msg);
        assertTrue(msg.length() <= 250);
    }

    @Test
    public void testMessageLengthFailure() {
        String msg = "a".repeat(300); // too long
        Chat.Message m = new Chat.Message("0837597589", msg);
        assertFalse(msg.length() <= 250);
    }

    @Test
    public void testMessageHashGeneration() {
        Chat.Message m = new Chat.Message("0837597589", "Hi Mike tonight");
        String hash = m.createMessageHash(1);
        assertEquals("01:HI:TONIGHT", hash);
    }

    @Test
    public void testSendMessageOptionSend() {
        Chat.Message m = new Chat.Message("0837597589", "Hello");
        String result = m.sendMessage("Send");
        assertEquals("Message successfully sent", result);
    }

    @Test
    public void testSendMessageOptionStore() {
        Chat.Message m = new Chat.Message("0837597589", "Hello");
        String result = m.sendMessage("Store");
        assertEquals("Message successfully stored", result);
    }

    @Test
    public void testSendMessageOptionDiscard() {
        Chat.Message m = new Chat.Message("0837597589", "Hello");
        String result = m.sendMessage("Discard");
        assertEquals("Press 0 to delete the message", result);
    }

    @Test
    public void testTotalMessagesCount() {
        Chat.Message m1 = new Chat.Message("0837597589", "Hello");
        m1.sendMessage("Send");
        Chat.Message m2 = new Chat.Message("0837597589", "Hi again");
        m2.sendMessage("Send");

        assertEquals(2, Chat.Message.returnTotalMessages());
    }
}


